[build]
  publish = "dist"
  command = "npm run build"

# Environment variables should be set in Netlify's UI under Site settings > Build & deploy > Environment variables
# VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY should be configured there
# [build.environment]
